apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/redhat-mal/assemble-platforms.git
        revision: enhance-gitops
        files:
        - path: "clusters/**/config.json"
  template:
    metadata:
      name: '{{"{{"}}cluster.name{{"}}"}}'
    spec:
      project: default
      source:
        path: charts/apps
        repoURL: https://github.com/redhat-mal/assemble-platforms.git
        targetRevision: enhance-gitops
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .Values.destination.namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
